<?php
    define('DBDRIVER','mysql');
    define('DBHOST','localhost');
    define('DBPORT',3306);
    define('DBNAME','i3_gift_box');
    define('DBCHARSET','utf8');
    define('DBUSER','root');
    define('DBPASS','');
?>